name: 'Tunet'
description: 'A modern, responsive dashboard for Home Assistant'
version: "1.15.2"
slug: 'tunet'
url: 'https://github.com/oyvhov/Tunet'
init: false
startup: application
arch:
  - aarch64
  - amd64
  - armv7
homeassistant_api: true
auth_api: true
ingress: true
ingress_port: 3002
panel_icon: 'mdi:view-dashboard-variant'
panel_title: 'Tunet'
ports:
  3002/tcp: null
ports_description:
  3002/tcp: 'Tunet Web Interface (not needed when using Ingress)'
options:
  data_encryption_mode: 'off'
  data_encryption_key: ''
  data_encryption_salt: ''
  tunet_public_mode_enabled: false
  tunet_public_ha_url: ''
  tunet_public_ha_token: ''
  tunet_public_read_only: false
schema:
  data_encryption_mode: 'list(off|dual|enc_only)?'
  data_encryption_key: 'password?'
  data_encryption_salt: 'password?'
  tunet_public_mode_enabled: 'bool?'
  tunet_public_ha_url: 'str?'
  tunet_public_ha_token: 'password?'
  tunet_public_read_only: 'bool?'
